# Generated by Django 4.2.5 on 2024-01-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AadharForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('Adhar_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AadharModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adhar_number', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Aadhar',
        ),
        migrations.DeleteModel(
            name='Adhar_detail',
        ),
    ]
