# Generated by Django 4.2.5 on 2024-01-17 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_aadharform_aadharmodel_delete_aadhar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('stu_name', models.CharField(max_length=100)),
                ('stu_address', models.CharField(max_length=200)),
                ('aadhar_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.aadharmodel')),
            ],
        ),
        migrations.DeleteModel(
            name='AadharForm',
        ),
        migrations.RenameField(
            model_name='aadharmodel',
            old_name='adhar_number',
            new_name='aadhar_no',
        ),
    ]
